config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :interviews
  get 'home/index'
  root to: 'home#index'

  resources :university_choices
  resources :placements do
	collection do
         post 'match'
  	end
  end
  resources :exam_results
  resources :exams
  resources :program_quota
  resources :program_choices
  resources :applicants
  resources :universities
  resources :programs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  
  has_many :placements
  has_many :program_quota
  has_many :program_choices
  has_many :waiting_lists

  def unplaced_applicants
      if total_remaining_quota > 0
        unvsts = program_quota.select{|x| remaining_quota(x.university_id) > 0}.collect{|x| x.university_id}

        return Applicant.joins([:exam=>:exam_results],[:program_choices=>:university_choices]).includes(:placement).
		where(placements: {id: nil}).where('exam_results.program_id = ? and program_choices.program_id = ? and university_choices.university_id in (?)',self.id,self.id, unvsts).uniq
    end
    return []
  end

  def remaining_quota(uninversity)
    return total_quota(uninversity) - total_placed(uninversity)
  end

  def total_placed(university)
    placements.where('university_id = ?',university).size
  end

  def total_quota(university)
    program_quota.where('university_id = ?',university).first.try(:quota_number) || 0
  end

  def count_applicants(choice_number)
    program_choices.where('choice_number = ?',choice_number).size
  end

  def total_remaining_quota
    University.all.collect{|x| remaining_quota(x.id)}.sum
  end

  def to_s
    name
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :program_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>