config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :interviews
  get 'home/index'
  root to: 'home#index'

  resources :university_choices
  resources :placements do
	collection do
         post 'match'
  	end
  end
  resources :exam_results
  resources :exams
  resources :program_quota
  resources :program_choices
  resources :applicants
  resources :universities
  resources :programs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program_choice.rb
class ProgramChoice < ApplicationRecord
  belongs_to :applicant
  belongs_to :program
  has_many :university_choices

  def to_s
    [applicant,program,choice_number].join('-')
  end
end

app/controllers/program_choices_controller.rb
class ProgramChoicesController < ApplicationController
  before_action :set_program_choice, only: [:show, :edit, :update, :destroy]

  # GET /program_choices
  # GET /program_choices.json
  def index
    @program_choices = ProgramChoice.all
  end

  # GET /program_choices/1
  # GET /program_choices/1.json
  def show
  end

  # GET /program_choices/new
  def new
    @program_choice = ProgramChoice.new
  end

  # GET /program_choices/1/edit
  def edit
  end

  # POST /program_choices
  # POST /program_choices.json
  def create
    @program_choice = ProgramChoice.new(program_choice_params)

    respond_to do |format|
      if @program_choice.save
        format.html { redirect_to @program_choice, notice: 'Program choice was successfully created.' }
        format.json { render :show, status: :created, location: @program_choice }
      else
        format.html { render :new }
        format.json { render json: @program_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /program_choices/1
  # PATCH/PUT /program_choices/1.json
  def update
    respond_to do |format|
      if @program_choice.update(program_choice_params)
        format.html { redirect_to @program_choice, notice: 'Program choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @program_choice }
      else
        format.html { render :edit }
        format.json { render json: @program_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /program_choices/1
  # DELETE /program_choices/1.json
  def destroy
    @program_choice.destroy
    respond_to do |format|
      format.html { redirect_to program_choices_url, notice: 'Program choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program_choice
      @program_choice = ProgramChoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_choice_params
      params.require(:program_choice).permit(:applicant_id, :program_id, :choice_number)
    end
end

app/helpers/program_choices_helper.rb
module ProgramChoicesHelper
end

app/views/program_choices/_form.html.erb
<%= form_with(model: program_choice, local: true) do |form| %>
  <% if program_choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program_choice.errors.count, "error") %> prohibited this program_choice from being saved:</h2>

      <ul>
      <% program_choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :applicant_id %>
    <%= form.collection_select(:applicant_id, Applicant.all, :id,:to_s, id: :program_choice_applicant_id) %>
  </div>

  <div class="field">
    <%= form.label :program_id %>
    <%= form.collection_select(:program_id,Program.all, :id, :name, id: :program_choice_program_id) %>
  </div>

  <div class="field">
    <%= form.label :choice_number %>
    <%= form.number_field :choice_number, id: :program_choice_choice_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/program_choices/edit.html.erb
<h1>Editing Program Choice</h1>

<%= render 'form', program_choice: @program_choice %>

<%= link_to 'Show', @program_choice %> |
<%= link_to 'Back', program_choices_path %>

app/views/program_choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Program Choices</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Program</th>
      <th>Choice number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @program_choices.each do |program_choice| %>
      <tr>
        <td><%= program_choice.applicant %></td>
        <td><%= program_choice.program %></td>
        <td><%= program_choice.choice_number %></td>
        <td><%= link_to 'Show', program_choice %></td>
        <td><%= link_to 'Edit', edit_program_choice_path(program_choice) %></td>
        <td><%= link_to 'Destroy', program_choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program Choice', new_program_choice_path %>

app/views/program_choices/new.html.erb
<h1>New Program Choice</h1>

<%= render 'form', program_choice: @program_choice %>

<%= link_to 'Back', program_choices_path %>

app/views/program_choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @program_choice.applicant %>
</p>

<p>
  <strong>Program:</strong>
  <%= @program_choice.program %>
</p>

<p>
  <strong>Choice number:</strong>
  <%= @program_choice.choice_number %>
</p>

<%= link_to 'Edit', edit_program_choice_path(@program_choice) %> |
<%= link_to 'Back', program_choices_path %>