config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :interviews
  get 'home/index'
  root to: 'home#index'

  resources :university_choices
  resources :placements do
	collection do
         post 'match'
  	end
  end
  resources :exam_results
  resources :exams
  resources :program_quota
  resources :program_choices
  resources :applicants
  resources :universities
  resources :programs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:aptitude_weight, :interview_weight, :exam_weight, :affirmative_percentage)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :aptitude_weight %>
    <%= form.text_field :aptitude_weight, id: :setting_aptitude_weight %>
  </div>

  <div class="field">
    <%= form.label :interview_weight %>
    <%= form.text_field :interview_weight, id: :setting_interview_weight %>
  </div>

  <div class="field">
    <%= form.label :exam_weight %>
    <%= form.text_field :exam_weight, id: :setting_exam_weight %>
  </div>
  
  <div class="field">
    <%= form.label :Female_affirmative_percentage %>
    <%= form.text_field :affirmative_percentage, id: :setting_affirmative_percentage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h3>Settings</h3><br/>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Aptitude weight</th>
      <th>Interview weight</th>
      <th>Exam weight</th>
      <th>Female affirmative percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.aptitude_weight %></td>
        <td><%= setting.interview_weight %></td>
        <td><%= setting.exam_weight %></td>
        <td><%= setting.affirmative_percentage %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aptitude weight:</strong>
  <%= @setting.aptitude_weight %>
</p>

<p>
  <strong>Interview weight:</strong>
  <%= @setting.interview_weight %>
</p>

<p>
  <strong>Exam weight:</strong>
  <%= @setting.exam_weight %>
</p>

<p>
  <strong>Female affirmative percentage:</strong>
  <%= @setting.affirmative_percentage %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>